#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SERVER_ROOT="${BOOST_GATEWAY_SERVER_ROOT:-"${REPO_ROOT}/../BoostAsioDemo"}"
SERVER_BUILD_DIR="${BOOST_GATEWAY_SERVER_BUILD_DIR:-"${SERVER_ROOT}/build"}"
BUILD_DIR="${BGTC_PACKAGE_BUILD_DIR:-"${REPO_ROOT}/build/package"}"

echo "=== BoostGatewayTankClient package ==="
echo "Build dir: ${BUILD_DIR}"
echo ""

# Configure and build
cmake -S "${REPO_ROOT}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DBOOST_GATEWAY_SERVER_ROOT="${SERVER_ROOT}" \
  -DBOOST_GATEWAY_SERVER_BUILD_DIR="${SERVER_BUILD_DIR}"
cmake --build "${BUILD_DIR}" --target boost_gateway_tank_client

# Version manifest (already generated by CMake configure_file)
MANIFEST="${BUILD_DIR}/version/version-manifest.json"
if [[ -f "${MANIFEST}" ]]; then
    echo ""
    echo "=== Version Manifest ==="
    cat "${MANIFEST}"
fi

# Run CPack
cmake --build "${BUILD_DIR}" --target package

echo ""
echo "=== Package output ==="
find "${BUILD_DIR}" -maxdepth 1 \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.dmg" -o -name "*.exe" \) -print

# Validate outputs
PACKAGE_COUNT=$(find "${BUILD_DIR}" -maxdepth 1 \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.dmg" -o -name "*.exe" \) | wc -l)
if [[ "${PACKAGE_COUNT}" -eq 0 ]]; then
    echo "ERROR: No package artifacts found!" >&2
    exit 1
fi

echo ""
echo "=== Package verification passed (${PACKAGE_COUNT} artifact(s)) ==="
